apiVersion: v1
kind: Template
metadata:
  name: f8osoproxy-config
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: f8osoproxy
  type: Opaque
  data:
    tenant.url: http://tenant:80
    auth.url: https://auth.prod-preview.openshift.io/api
    traefik.toml: ""

- apiVersion: v1
  kind: Secret
  metadata:
    name: f8osoproxy
  type: Opaque
  data:
    service.account.id: YzIxMWYxYmQtMTdhNy00ZjhjLTlmODAtMDkxN2QxNjc4ODlk
    service.account.secret: dGVuYW50c2VjcmV0bmV3
    auth.token.key: dGVuYW50c2VjcmV0bmV3
    