---
apiVersion: v1
kind: Template
metadata:
  name: fabric8-oso-sproxy
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: f8osoproxy
    name: f8osoproxy
  spec:
    replicas: 1
    selector:
      app: f8osoproxy
      deploymentconfig: f8osoproxy
    strategy:
      resources:
        limits:
          memory: 1Gi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: f8osoproxy
          deploymentconfig: f8osoproxy
      spec:
        containers:
        - env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: f8osoproxy
                key: database.url
          image: registry.devshift.net/fabric8-services/fabric8-oso-proxy:${IMAGE_TAG}
          imagePullPolicy: Always
          name: f8osoproxy
          ports:
          - containerPort: 4242
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 4242
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 4242
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: f8osoproxy
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 4242
    selector:
      deploymentconfig: f8osoproxy
parameters:
- name: IMAGE_TAG
  value: latest
